spring:
  datasource:
    url: jdbc:mysql://localhost:3306/point-edge?createDatabaseIfNotExist=true
    username: root
    password: 20020818
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: pointedgeforyou@gmail.com
    password: eaih glmg elgc vkrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000