spring:
  datasource:
    url: jdbc:mysql://localhost:3306/point-edge?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: pointedgeforyou@gmail.com
    password: eaih glmg elgc vkrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
stripe:
  secret:
    key: sk_test_51Rl11VFgHQWIbBdJCTGP9yvshanIOpGg9vqfWRoilU0rcHAuogyADhxr52ygt6cts9SZoHRR8KJDbmsWnb1U7EAn00hgs18Vlq
  api:
    base:
      url: https://api.stripe.com
payment:
  currency: LKR
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 20MB
