spring:
  datasource:
    url: jdbc:mysql://localhost:3306/point-edge?createDatabaseIfNotExist=true
    username: root
    password: 20020818
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.eternalcoders.pointedge: DEBUG
